### ISSUE TITLE
Finish babel implementation

### ISSUE THREAD

**Issue by joostlawerman** [joostlawerman/SnackbarLightjs#2]
Finish the current babel implementation located on the babel branch.

**Comment by rowlandekemezie** [comment]
@joostlawerman can you provide description for the task. I'm willing to help you - `help wanted` 😄

**Comment by joostlawerman** [comment]
@andela-rekemezie There are still some problems with the babel implementation for instance some of the features are not working correctly. Also seperating the Snackbar and Timer class in a seperate file does not seem to realy work becouse you will get: 

> Uncaught ReferenceError: module is not defined

**Comment by jwarykowski** [comment]
@joostlawerman have you also thought about using webpack...? @andela-rekemezie have you already started development here?

**Comment by joostlawerman** [comment]
@jonathanchrisp I am not really experienced with webpack. Currently I'm using gulp to compile the babel code to JS. If you have a good solution/ example with webpack I would be happy to implement it.

**Comment by marcelorl** [comment]
I'd be happy to convert the code to es6 and bundle it with webpack.
Anyone has started anything in here or I may start it?

**Comment by joostlawerman** [comment]
@marcelorl most of the code is already converted on the [babel](https://github.com/joostlawerman/SnackbarLightjs/tree/babel) branch. Only some functions are malfunctioning and there is no webpack yet.

**Comment by marcelorl** [comment]
True. Sorry.

So I can help with bug fixing and webpack then. What do you think?

**Comment by joostlawerman** [comment]
Sure just fork the repo and open a pull request.

**Comment by Costava** [comment]
What still needs to be done?

The setup to bundle `snackbar.js` and `timer.js` with `snackbarlight.js` using webpack and output to `dist/snackbarlight.js` and `dist/snackbarlight.min.js` accordingly?

**Comment by joostlawerman** [comment]
@Costava Yes exactly.

**Comment by joostlawerman** [comment]
Fixed in #3
